before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/cuebe
    ldflags:
      - -s -w
      - -X github.com/loft-orbital/cuebe/cmd/cuebe/cmd.version={{.Version}}
      - -X github.com/loft-orbital/cuebe/cmd/cuebe/cmd.commit={{.Commit}}
      - -X github.com/loft-orbital/cuebe/cmd/cuebe/cmd.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^chore:'
      - '^ci:'
      - '^docs:'
      - '^style:'
      - '^test:'
release:
  footer: |
    _not only space made simple 🛰️_
  prerelease: auto
announce:
  slack:
    enabled: true
    message_template: 'I redefined {{ .ProjectName }} identity. New version {{ .Tag }} available at {{ .GitURL }}/releases/tag/{{ .Tag }}'
